# Generated by Django 3.2.4 on 2021-06-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_create', models.DateTimeField(auto_now=True)),
                ('order_name', models.CharField(max_length=200)),
                ('order_phone', models.CharField(max_length=200)),
            ],
        ),
    ]
